### ISSUE TITLE
Update Basic Authentication Query

### ISSUE THREAD

**Issue by wtroddy** [OHDSI/Broadsea#107]
While trying to configure OIDC security (related issue: https://github.com/OHDSI/WebAPI/issues/2304) I discovered that the "basic authentication" using Broadsea-Atlasdb has the [WebAPI security schema/table](https://github.com/OHDSI/Broadsea-Atlasdb/blob/main/080_create_and_populate_webapi_security_schema.sql) configured slightly differently than the expected defaults. When using the current settings this error gets raised:

```
ERROR:  relation "ohdsi.users_data" does not exist at character 22
STATEMENT:  select password from ohdsi.users_data where lower(email) = lower($1)
```

It looks like one solution is to set this explicitly through the `SECURITY_DB_DATASOURCE_AUTHENTICATIONQUERY` environment variable. 

I added this to .env:

```.env
SECURITY_DB_DATASOURCE_AUTHENTICATIONQUERY="select password from webapi_security.security where lower(email) = lower(?);"
```

And passed those along in ohdsi-webapi.yml:

```yml
SECURITY_DB_DATASOURCE_AUTHENTICATIONQUERY: ${SECURITY_DB_DATASOURCE_AUTHENTICATIONQUERY}
```

and that seems to have resolved the issue. Alternatively, the base query could be written in ohdsi-webapi.yml and then the env vars for schema/table could be re-used. 

I'd be happy to create an PR for this if you'd like - just let me know which branch to target.

**Comment by alondhe** [comment]
Thanks @wtroddy -- can you target the develop branch? We're finalizing 3.1 stuff there for release.

**Comment by wtroddy** [comment]
Hi @alondhe - sure, happy to do that. I'll try to get to it this week sometime.

**Comment by alondhe** [comment]
Any luck, @wtroddy ?

**Comment by wtroddy** [comment]
@alondhe - sorry about the delay here. I just started a PR (#113) with these changes. 

One question I have - there was a conflict in the password setup for the db vs. the secret file that was defined. It looks like there's one the postgres user created for that db right now and the password is getting set in docker-compose.yml (`POSTGRES_PASSWORD`). Is that change okay or would you like it handled differently?

I also went ahead and added some additional docs and default values that I would've found useful when first trying to get this configured. Let me know if you want those removed/moved/changed in any way.  

Can you review the changes and let me know if there's any other changes you'd like made?
