### ISSUE TITLE
Does broadsea2 support ARM?

### ISSUE THREAD

**Issue by gslin1224** [OHDSI/Broadsea#115]
I tried to build broadsea 2.0 on my MacBook with an M2 chip, but I always encounter errors.

Thank you all!

traefik           | time="2023-11-18T17:58:11Z" level=error msg="service \"ohdsi-webapi-broadsea2\" error: unable to find the IP address for the container \"/ohdsi-webapi\": the server is ignored" providerName=docker container=ohdsi-webapi-broadsea2-ecd52ccea298d4dc30ef0498279284f96e668430ad01e7cfe243fb5334d101bf

<img width="648" alt="截圖 2023-11-19 上午1 58 34" src="https://github.com/OHDSI/Broadsea/assets/151395340/b10f34ab-e175-4435-8ece-bdf6035b7929">

<img width="586" alt="image" src="https://github.com/OHDSI/Broadsea/assets/151395340/b60b8f1c-924c-4f28-a0c5-fd45f702b205">

**Comment by haydenbspence** [comment]
Yes!

Line 5 of the env file is what you're looking for. Change it to this:

DOCKER_ARCH="linux/arm64"

**Comment by gslin1224** [comment]
> Yes!
> 
> Line 5 of the env file is what you're looking for. Change it to this:
> 
> DOCKER_ARCH="linux/arm64"

thank your reply.
I did this on broadsea 3.0 env is working, but 2.0 env have difference,it env is doesn't have DOCKER_ARCH.
I tried add that, but doesn't work too.

**Comment by haydenbspence** [comment]
> > Yes!
> 
> > 
> 
> > Line 5 of the env file is what you're looking for. Change it to this:
> 
> > 
> 
> > DOCKER_ARCH="linux/arm64"
> 
> 
> 
> thank your reply.
> 
> I did this on broadsea 3.0 env is working, but 2.0 env have difference,it env is doesn't have DOCKER_ARCH.
> 
> I tried add that, but doesn't work too.
> 
> 

You're right, looking at v2 the option for ARM was implemented after for v3.

Can I ask why you can't use v3? 

It would be possible to use ARM for v2, but it may be more work than just migrating to v3.

**Comment by gslin1224** [comment]
> > > Yes!
> > 
> > 
> > > 
> > 
> > 
> > > Line 5 of the env file is what you're looking for. Change it to this:
> > 
> > 
> > > 
> > 
> > 
> > > DOCKER_ARCH="linux/arm64"
> > 
> > 
> > thank your reply.
> > I did this on broadsea 3.0 env is working, but 2.0 env have difference,it env is doesn't have DOCKER_ARCH.
> > I tried add that, but doesn't work too.
> 
> You're right, looking at v2 the option for ARM was implemented after for v3.
> 
> Can I ask why you can't use v3?
> 
> It would be possible to use ARM for v2, but it may be more work than just migrating to v3.

because I'm doing a project, and this project is build on v2,so I need build v2 on my MacBook.

**Comment by pcjustin** [comment]
Hello everyone,

I had the same problem with the M1 chip.
I know v2 cannot support M1, but if I connect a v2 machine, is v3 compatible with v2?

**Comment by gslin1224** [comment]
> @pcjustin I don't understand, are you asking if v3 Broadsea is compatible with v2?
> 
> @gslin1224 I am not able to test myself (don't have any M chip/ARM systems), but please try this:
> 
> Modify the docker-compose.yml file and place "platform: linux/arm64" under image: for each container. If that doesn't work, try only making the addition for broadsea-content, broadsea-hades, ohdsi-atlas, ohdsi-webapi, broadsea-atlas -- leave the others list nginx and traefik the same.
> 
> Let me know if that works!
> 
> Full example:
> 
> `version: '3'
> 
> volumes: atlasdb-postgres-data: name: atlasdb-postgres-data rstudio-home-data: name: rstudio-home-data rstudio-tmp-data: name: rstudio-tmp-data
> 
> services:
> 
> traefik: image: docker.io/library/traefik:v2.9.4@sha256:4c388f477f5b7aa48420694d90db0ecb96b4ecede60b9b7589c87858abf87b60 container_name: traefik platform: linux/arm64 restart: unless-stopped ipc: none read_only: true command: - "--providers.docker=true" - "--providers.docker.exposedbydefault=false" - "--entrypoints.web.address=:80" labels: - "traefik.enable=true" ports: - "${BROADSEA_HOST}:80:80" volumes: - "/var/run/docker.sock:/var/run/docker.sock:ro"
> 
> broadsea-content: container_name: broadsea-content image: nginx platform: linux/arm64 restart: unless-stopped volumes: - ./broadsea-content:/usr/share/nginx/html/broadsea:ro labels: - "traefik.enable=true" - "traefik.http.routers.nginx.rule=Host(`${BROADSEA_HOST}`) && PathPrefix(`/broadsea`)" - "traefik.http.routers.nginx.entrypoints=web"
> 
> broadsea-hades: container_name: broadsea-hades image: ohdsi/broadsea-hades:4.2.1 platform: linux/arm64 environment: - USER=ohdsi - PASSWORD=mypass volumes: - rstudio-home-data:/home - rstudio-tmp-data:/tmp labels: - "traefik.enable=true" - "traefik.http.routers.broadsea-hades.rule=Host(`${BROADSEA_HOST}`) && PathPrefix(`/`)" - "traefik.http.routers.broadsea-hades.entrypoints=web" - "traefik.http.services.broadsea-hades.loadbalancer.server.port=8787" ports: - "8787:8787" - "6311:6311"
> 
> ohdsi-atlas: container_name: ohdsi-atlas image: docker.io/ohdsi/atlas:latest platform: linux/arm64 restart: unless-stopped ipc: none privileged: false environment: WEBAPI_URL: "http://${BROADSEA_HOST}/WebAPI/" depends_on: - ohdsi-webapi labels: - "traefik.enable=true" - "traefik.http.routers.ohdsi-atlas.rule=Host(`${BROADSEA_HOST}`) && PathPrefix(`/atlas`)" - "traefik.http.routers.ohdsi-atlas.entrypoints=web"
> 
> ohdsi-webapi: container_name: ohdsi-webapi image: docker.io/ohdsi/webapi:latest platform: linux/arm64 restart: unless-stopped ipc: none read_only: true tmpfs: - /tmp privileged: false environment: DATASOURCE_DRIVERCLASSNAME: org.postgresql.Driver DATASOURCE_URL: jdbc:postgresql://broadsea-atlasdb:5432/postgres DATASOURCE_USERNAME: postgres DATASOURCE_PASSWORD: mypass DATASOURCE_OHDSI_SCHEMA: webapi SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.PostgreSQLDialect SPRING_JPA_PROPERTIES_HIBERNATE_DEFAULT_SCHEMA: webapi SPRING_BATCH_REPOSITORY_TABLEPREFIX: webapi.BATCH_ FLYWAY_DATASOURCE_DRIVERCLASSNAME: org.postgresql.Driver FLYWAY_DATASOURCE_URL: jdbc:postgresql://broadsea-atlasdb:5432/postgres FLYWAY_DATASOURCE_USERNAME: postgres FLYWAY_DATASOURCE_PASSWORD: postgres FLYWAY_LOCATIONS: classpath:db/migration/postgresql FLYWAY_PLACEHOLDERS_OHDSISCHEMA: webapi FLYWAY_SCHEMAS: webapi FLYWAY_BASELINEONMIGRATE: "true" FLYWAY_TABLE: schema_history flyway_baselineVersionAsString: "2.2.5.20180212152023" # this env var is case sensitive FLYWAY_BASELINEDESCRIPTION: Base Migration SECURITY_CORS_ENABLED: "true" SECURITY_ORIGIN: "http://${BROADSEA_HOST}" depends_on: - broadsea-atlasdb labels: - "traefik.enable=true" - "traefik.http.routers.ohdsi-webapi.rule=Host(`${BROADSEA_HOST}`) && PathPrefix(`/WebAPI`)" - "traefik.http.routers.ohdsi-webapi.entrypoints=web"
> 
> broadsea-atlasdb: image: ohdsi/broadsea-atlasdb:2.0.0 container_name: broadsea- platform: linux/arm64 cpus: 2 mem_limit: "2G" environment: - POSTGRES_PASSWORD=mypass ports: - "5432:5432" volumes: - atlasdb-postgres-data:/var/lib/postgresql/data - ./100_populate_source_source_daimon.sql:/docker-entrypoint-initdb.d/100_populate_source_source_daimon.sql:ro healthcheck: test: ["CMD-SHELL", "pg_isready -U postgres"] interval: 5s timeout: 5s retries: 10 `

do you mean replace yml?
I do this, but when I docker compose up run error

Last login: Wed Nov 22 01:26:41 on console
lin@linguanxundeMacBook-Air ~ % cd broadsea2
lin@linguanxundeMacBook-Air broadsea2 % docker compose up
parsing /Users/lin/broadsea2/docker-compose.yml: yaml: unmarshal errors:
  line 28: mapping key "volumes" already defined at line 3
  line 36: mapping key "volumes" already defined at line 3
  line 50: mapping key "volumes" already defined at line 3
  line 127: mapping key "volumes" already defined at line 3
  line 7: mapping key "name" already defined at line 5
  line 9: mapping key "name" already defined at line 5
  line 9: mapping key "name" already defined at line 7
  line 33: mapping key "image" already defined at line 14
  line 45: mapping key "image" already defined at line 14
  line 64: mapping key "image" already defined at line 14
  line 80: mapping key "image" already defined at line 14
  line 118: mapping key "image" already defined at line 14
  line 32: mapping key "container_name" already defined at line 15
  line 44: mapping key "container_name" already defined at line 15
  line 63: mapping key "container_name" already defined at line 15
  line 79: mapping key "container_name" already defined at line 15
  line 119: mapping key "container_name" already defined at line 15
  line 34: mapping key "platform" already defined at line 16
  line 46: mapping key "platform" already defined at line 16
  line 65: mapping key "platform" already defined at line 16
  line 81: mapping key "platform" already defined at line 16
  line 120: mapping key "platform" already defined at line 16
  line 35: mapping key "restart" already defined at line 17
  line 66: mapping key "restart" already defined at line 17
  line 82: mapping key "restart" already defined at line 17
  line 67: mapping key "ipc" already defined at line 18
  line 83: mapping key "ipc" already defined at line 18
  line 84: mapping key "read_only" already defined at line 19
  line 38: mapping key "labels" already defined at line 24
  line 53: mapping key "labels" already defined at line 24
  line 73: mapping key "labels" already defined at line 24
  line 112: mapping key "labels" already defined at line 24
  line 58: mapping key "ports" already defined at line 26
  line 125: mapping key "ports" already defined at line 26
  line 36: mapping key "volumes" already defined at line 28
  line 50: mapping key "volumes" already defined at line 28
  line 127: mapping key "volumes" already defined at line 28
  line 44: mapping key "container_name" already defined at line 32
  line 63: mapping key "container_name" already defined at line 32
  line 79: mapping key "container_name" already defined at line 32
  line 119: mapping key "container_name" already defined at line 32
  line 45: mapping key "image" already defined at line 33
  line 64: mapping key "image" already defined at line 33
  line 80: mapping key "image" already defined at line 33
  line 118: mapping key "image" already defined at line 33
  line 46: mapping key "platform" already defined at line 34
  line 65: mapping key "platform" already defined at line 34
  line 81: mapping key "platform" already defined at line 34
  line 120: mapping key "platform" already defined at line 34
  line 66: mapping key "restart" already defined at line 35
  line 82: mapping key "restart" already defined at line 35
  line 50: mapping key "volumes" already defined at line 36
  line 127: mapping key "volumes" already defined at line 36
  line 53: mapping key "labels" already defined at line 38
  line 73: mapping key "labels" already defined at line 38
  line 112: mapping key "labels" already defined at line 38
  line 63: mapping key "container_name" already defined at line 44
  line 79: mapping key "container_name" already defined at line 44
  line 119: mapping key "container_name" already defined at line 44
  line 64: mapping key "image" already defined at line 45
  line 80: mapping key "image" already defined at line 45
  line 118: mapping key "image" already defined at line 45
  line 65: mapping key "platform" already defined at line 46
  line 81: mapping key "platform" already defined at line 46
  line 120: mapping key "platform" already defined at line 46
  line 69: mapping key "environment" already defined at line 47
  line 88: mapping key "environment" already defined at line 47
  line 123: mapping key "environment" already defined at line 47
  line 127: mapping key "volumes" already defined at line 50
  line 73: mapping key "labels" already defined at line 53
  line 112: mapping key "labels" already defined at line 53
  line 125: mapping key "ports" already defined at line 58
  line 79: mapping key "container_name" already defined at line 63
  line 119: mapping key "container_name" already defined at line 63
  line 80: mapping key "image" already defined at line 64
  line 118: mapping key "image" already defined at line 64
  line 81: mapping key "platform" already defined at line 65
  line 120: mapping key "platform" already defined at line 65
  line 82: mapping key "restart" already defined at line 66
  line 83: mapping key "ipc" already defined at line 67
  line 87: mapping key "privileged" already defined at line 68
  line 88: mapping key "environment" already defined at line 69
  line 123: mapping key "environment" already defined at line 69
  line 110: mapping key "depends_on" already defined at line 71
  line 112: mapping key "labels" already defined at line 73
  line 119: mapping key "container_name" already defined at line 79
  line 118: mapping key "image" already defined at line 80
  line 120: mapping key "platform" already defined at line 81
  line 123: mapping key "environment" already defined at line 88
lin@linguanxundeMacBook-Air broadsea2 %

**Comment by gslin1224** [comment]
I try only add linux/arm64 but same

 image with reference docker.io/ohdsi/broadsea-atlasdb:2.0.0 was found but does not match the specified platform: wanted linux/arm64, actual: linux/amd64
lin@linguanxundeMacBook-Air broadsea2 %

**Comment by haydenbspence** [comment]
> I try only add linux/arm64 but same
> 
> image with reference docker.io/ohdsi/broadsea-atlasdb:2.0.0 was found but does not match the specified platform: wanted linux/arm64, actual: linux/amd64 lin@linguanxundeMacBook-Air broadsea2 %

Ok, it looks like only some of the Broadsea containers are built for arm64. Even for Broadsea V3 this is the case. This will require a more involved update for V2 and V3.

If you need to use V2 on arm64 soon, I would suggest virtualization with [Colima](https://github.com/abiosoft/colima/). Here is a [tutorial on setting it up and getting docker compose working](https://smallsharpsoftwaretools.com/tutorials/use-colima-to-run-docker-containers-on-macos/). It will not perform nearly as well as arm64 built containers running natively, but it should be enough for development.

@leeevans @alondhe this may be another reason we switch to using a base image of the same LTS Ubuntu as Rocker for all services. I believe they are currently at Jammy. We could then use[github-actions to build multiplatform](https://docs.docker.com/build/ci/github-actions/multi-platform/)

**Comment by gslin1224** [comment]
> > I try only add linux/arm64 but same
> > image with reference docker.io/ohdsi/broadsea-atlasdb:2.0.0 was found but does not match the specified platform: wanted linux/arm64, actual: linux/amd64 lin@linguanxundeMacBook-Air broadsea2 %
> 
> Ok, it looks like only some of the Broadsea containers are built for arm64. Even for Broadsea V3 this is the case. This will require a more involved update for V2 and V3.
> 
> If you need to use V2 on arm64 soon, I would suggest virtualization with [Colima](https://github.com/abiosoft/colima/). Here is a [tutorial on setting it up and getting docker compose working](https://smallsharpsoftwaretools.com/tutorials/use-colima-to-run-docker-containers-on-macos/). It will not perform nearly as well as arm64 built containers running natively, but it should be enough for development.
> 
> @leeevans @alondhe this may be another reason we switch to using a base image of the same LTS Ubuntu as Rocker for all services. I believe they are currently at Jammy. We could then use[github-actions to build multiplatform](https://docs.docker.com/build/ci/github-actions/multi-platform/)

Hey bro, can I have your email?

**Comment by alondhe** [comment]
We do need to harmonize the architectures so that we can offer amd and arm consistently. I think we'd need to target a 3.2 release for this, though. But with the various Mac Silicon improvements in Docker, it will still run with some services on amd and others on arm just fine.

**Comment by gslin1224** [comment]
> We do need to harmonize the architectures so that we can offer amd and arm consistently. I think we'd need to target a 3.2 release for this, though. But with the various Mac Silicon improvements in Docker, it will still run with some services on amd and others on arm just fine.我們確實需要協調架構，以便我們可以一致地提供 amd 和 arm。不過，我認為我們需要為此瞄準 3.2 版本。但是隨著 Docker 中各種 Mac Silicon 的改進，它仍然可以在 amd 上運行一些服務，而在 arm 上運行其他服務就可以了。

Exactly, Broadsea2 can run on ARM. There is a bug in the docker-compose.yml file.
<img width="518" alt="image" src="https://github.com/OHDSI/Broadsea/assets/151395340/505a133d-9cd9-4ce3-8f9d-53abd485a148">
The password should be "mypass," not "postgres."

**Comment by alondhe** [comment]
We aren't supporting Broadsea 2 any further. 

I'd suggest using Broadsea 3.1 (currently in develop branch).
