### ISSUE TITLE
Which Broadsea repositories are actively in development?

### ISSUE THREAD

**Issue by anthonysena** [OHDSI/Broadsea#117]
Question for @leeevans: there are a number of other OHDSI Broadsea repos (i.e. https://github.com/OHDSI/Broadsea-WebTools). Should the community use this Broadsea repo and/or the other repos based on specific use cases? Can you help clarify?

Tagging @davidhcar

**Comment by leeevans** [comment]
Broadsea-WebTools is deprecated.

Broadsea 3.0 uses the ohdsi/webapi docker image built in a github action in:
https://github.com/OHDSI/WebAPI
and the ohdsi/atlas docker image built in a github action in:
https://github.com/OHDSI/Atlas/

Broadsea 3.0 scripts are maintained here:
https://github.com/OHDSI/Broadsea

The plan is that broadsea-methodslibrary will be deprecated when a github action to build the ohdsi/hades docker image is added to:
https://github.com/OHDSI/Hades

**Comment by anthonysena** [comment]
Thanks @leeevans this is helpful!

**Comment by alondhe** [comment]
Agreed, once we finish the 3.1 release, I would like to begin deprecating the repos that aren't in Broadsea. Given profiles, we don't need to have multiple repos, just this one.
