### ISSUE TITLE
Running Broadsea with existing prepopulated WebAPI DB fails due to migrations running despite FLYWAY_BASELINE_ON_MIGRATE="false"

### ISSUE THREAD

**Issue by vcolano** [OHDSI/Broadsea#134]
I have an OHDSI stack running which was deployed using https://github.com/OHDSI/OHDSIonAWS. I'm interested in migrating our deployment to Broadsea.

This deployment's WebAPI DB is running in an RDS Aurora postgres DB and already has the WebAPI schemas/tables created with real application data (cohorts, concept sets, etc). I cloned this DB to a new RDS Aurora postgres instance, and am able to connect it locally.

In my local Broadsea configuration, I've updated 
https://github.com/OHDSI/Broadsea/blob/6e834eda7a187ff8def7134ee999055af2b81edd/.env#L58-L62
with the connection parameters for my DB and set 
https://github.com/OHDSI/Broadsea/blob/6e834eda7a187ff8def7134ee999055af2b81edd/.env#L48
to `"false"`.

When I run Broadsea with `docker-compose --profile default up -d  --force-recreate` I am getting errors in the `ohdsi/webapi` container from the flyway migration because the DB objects it tries to create already exist. I do not understand why any migration is running at all, my expectation was that by setting `FLYWAY_BASELINE_ON_MIGRATE="false"` no migration would not be run (because the DB is already populated).

I believe my issue is related to this issue: https://github.com/OHDSI/Broadsea/issues/85

**Comment by leeevans** [comment]
@vcolano For the record, check that your flyway schema table in your postgres database is called "schema_history" so that flyway can find it when Broadsea starts the WebAPI container.

You may need to rename your existing table.

The table name is set with that value in this Broadsea file:  ./compose/ohdsi-webapi.yml

FLYWAY_TABLE: schema_history
