### ISSUE TITLE
Adding Postgres container to compose 

### ISSUE THREAD

**Issue by K1Hyve** [OHDSI/Broadsea#14]
Hey, I'm new to OHDSI tools and community so I don't have much knowledge about its internal architecture but I'm wondering does it make sense to run Postgres via Docker and add it to the `docker-compose.yml` in `postgresql` directory or it should be an external entity?

**Comment by leeevans** [comment]
@K1Hyve either approach can be used. If you add postgresql to the docker-compose file you will need to add a dependency so the postgresql database is up and running before Atlas starts.

**Comment by K1Hyve** [comment]
I see, thanks for the info. Then I'll add Postgres to `docker-compose.yml` in my fork and if it's useful I can send a PR here as well.
