### ISSUE TITLE
DuplicateKeyException

### ISSUE THREAD

**Issue by martinchapman** [OHDSI/Broadsea#18]
Hello --

Many thanks for contributing the Broadsea images.

I've installed everything as per the quick start guide, and I'm using version 5.2.2 of the CDM to allow me to load the SynPUF dataset.

When trying to generate a cohort using Atlas, much like OHDSI/Broadsea#13, I found the need to add a `mode_id` column to the following results tables:

```sql
ALTER TABLE ohdsi.cohort_inclusion_result ADD mode_id int NOT NULL DEFAULT 0;
ALTER TABLE ohdsi.cohort_inclusion_stats ADD mode_id int NOT NULL DEFAULT 0;
ALTER TABLE ohdsi.cohort_summary_stats ADD mode_id int NOT NULL DEFAULT 0;
```

However, after doing this, I was then met with an additional constraint violation error (DuplicateKeyException) during cohort generation, seemingly due to the underlying SQL queries attempting to insert records with the same `cohort_definition_id` (primary key) into the above three tables multiple times, e.g.:

1. During cohort generation, a record is inserted into `cohort_inclusion_stats` with a `cohort_definition_id` of 4:
```sql
insert into ohdsi.cohort_inclusion_stats (cohort_definition_id, rule_sequence, person_count, gain_count, person_total, mode_id) select ir.cohort_definition_id, ir.rule_sequence, coalesce(T.person_count, 0) as person_count, coalesce(SR.person_count, 0) gain_count, EventTotal.total, 0 as mode_id from ohdsi.cohort_inclusion ir left join (select i.inclusion_rule_id, COUNT(i.event_id) as person_count from qualified_events Q JOIN inclusion_events i on Q.person_id = I.person_id and Q.event_id = i.event_id group by i.inclusion_rule_id) T on ir.rule_sequence = T.inclusion_rule_id CROSS JOIN (select count(*) as total_rules from ohdsi.cohort_inclusion where cohort_definition_id = 4) RuleTotal CROSS JOIN (select COUNT(event_id) as total from qualified_events) EventTotal LEFT JOIN ohdsi.cohort_inclusion_result SR on SR.mode_id = 0 AND SR.cohort_definition_id = 4 AND (POWER(cast(2 as bigint),RuleTotal.total_rules) - POWER(cast(2 as bigint),ir.rule_sequence) - 1) = SR.inclusion_rule_mask; 
```

2. Later on in the same generation, an attempt is made to add another record to `cohort_inclusions_stats` also with a `cohort_definition_id` of 4, triggering the exception:

```sql
insert into ohdsi.cohort_inclusion_stats (cohort_definition_id, rule_sequence, person_count, gain_count, person_total, mode_id) select ir.cohort_definition_id, ir.rule_sequence, coalesce(T.person_count, 0) as person_count, coalesce(SR.person_count, 0) gain_count, EventTotal.total, 1 as mode_id from ohdsi.cohort_inclusion ir left join (select i.inclusion_rule_id, COUNT(i.event_id) as person_count from best_events Q JOIN inclusion_events i on Q.person_id = I.person_id and Q.event_id = i.event_id group by i.inclusion_rule_id) T on ir.rule_sequence = T.inclusion_rule_id CROSS JOIN (select count(*) as total_rules from ohdsi.cohort_inclusion where cohort_definition_id = 4) RuleTotal CROSS JOIN (select COUNT(event_id) as total from best_events) EventTotal LEFT JOIN ohdsi.cohort_inclusion_result SR on SR.mode_id = 1 AND SR.cohort_definition_id = 4 AND (POWER(cast(2 as bigint),RuleTotal.total_rules) - POWER(cast(2 as bigint),ir.rule_sequence) - 1) = SR.inclusion_rule_mask;
```

I initially assumed this was due to a poorly defined cohort, but in OHDSI/Broadsea#13 the logs seem to show the same constraint violation taking place, yet a similar exception is not reported. Are there therefore some additional steps that ought to be undertaken to enable cohort generation to work? Perhaps certain constraints need to be altered?

I'm marking this as an issue on the off-chance it's indicative of an underlying bug.

Thanks in advance.

**Comment by LeonKalderon** [comment]
I'm facing the exact same issue and I was wondering if it was just me.

**Comment by martinchapman** [comment]
One solution, which I'm running in parallel, is to download a results DDL from by the WebAPI directly (e.g., http://localhost:8080/WebAPI/ddl/results?dialect=postgresql), and to then use this to populate a new results schema, as suggested [here](https://forums.ohdsi.org/t/cohort-generation-in-atlas-with-generation-status-failed/5690/26). The results source daimon entry for the results tables can then be updated [here](https://github.com/OHDSI/Broadsea/blob/4d2d74a56058581401056d4c0a1b9a2360701fe9/postgresql/source_source_daimon.sql#L17) (switching from 'ohdsi' to 'results'), effectively circumventing the standard results tables produced by the WebAPI migration.

However, as this isn't mentioned in the setup guide, and solves the issue by essentially dropping the primary keys on these tables, I still went ahead and opened this issue.

**Comment by LeonKalderon** [comment]
Hello @martinchapman,

Thanks for your reply, I'd already tried that and the problem have not been solved.
Did that worked from you? 

Particularly, the steps that I followed:
1. Create a new schema named results
2. Execute all the queries found in http://localhost:8080/WebAPI/ddl/results?dialect=postgresql by replacing `vocab` with the schema that I have my vocabulary. (All queries where run successfully)
3. Updated `ohdsi.source_daimon.`table_qualifier` with value `results` in `source_daimon` record with `daimon_type=2`.
4. Restart webtools container 

Thanks for your time :)

**Comment by martinchapman** [comment]
Yes, those steps worked for me.

I've pushed a copy of our working configuration here: https://github.com/kclhi/ohdsi.

Cross-checking this with your configuration may help?

**Comment by LeonKalderon** [comment]
After a few restarts it finally worked, without doing any further actions.

Also I had a look at the repo you sent me and there are some useful things that may help me organize my project better. 

Thanks a lot, I really appreciate your help :)

**Comment by martinchapman** [comment]
Great, no worries.
