### ISSUE TITLE
docker build is failing

### ISSUE THREAD

**Issue by leeevans** [OHDSI/Broadsea#2]
The standard docker build is failing for this container on dockerhub:
https://hub.docker.com/r/ohdsi/development/builds/bxs5jwjf32mn67kqhypum6j/
I get the same error when I try to do a docker build locally.

It seems to be an issue with the Cyclops compilation within the rocker/hadleyverse container. (Cyclops compiles fine in travis and jenkins).

**Comment by msuchard** [comment]
The base docker container now appears (?) to use GCC >5.  Will update headers in C/C++ components of our R packages.

**Comment by msuchard** [comment]
Fixed via Cyclops commit 89fb3f6ba614ebfcca4e7b65c7414fa9854d9860
