### ISSUE TITLE
Initial installation on ubuntu fails on step "Creating ohdsi_broadsea-webtools_1"

### ISSUE THREAD

**Issue by gkovaig** [OHDSI/Broadsea#20]
Environment: Ubuntu 20.04, Docker version 19.03.12, docker-compose version 1.26.1
rm@rm-desktop:~/dev/ohdsi$ sudo docker-compose up -d

Excerpt from console messages:
ohdsi_broadsea-methods-library_1 is up-to-date
Starting ohdsi_broadsea-webtools_1 ... error

ERROR: for ohdsi_broadsea-webtools_1  Cannot start service broadsea-webtools: OCI runtime create failed: container_linux.go:349: starting container process caused "process_linux.go:449: container init caused \"rootfs_linux.go:58: mounting \\\"/home/rm/dev/ohdsi/config-local.js\\\" to rootfs \\\"/var/lib/docker/overlay2/fe367cc697a94e768b966c7c750a5611cde1c1461ceb2ec091590d0bc178f59a/merged\\\" at \\\"/var/lib/docker/overlay2/fe367cc697a94e768b966c7c750a5611cde1c1461ceb2ec091590d0bc178f59a/merged/usr/local/tomcat/webapps/atlas/js/config-local.js\\\" caused \\\"not a directory\\\"\"": unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type

ERROR: for broadsea-webtools  Cannot start service broadsea-webtools: OCI runtime create failed: container_linux.go:349: starting container process caused "process_linux.go:449: container init caused \"rootfs_linux.go:58: mounting \\\"/home/rm/dev/ohdsi/config-local.js\\\" to rootfs \\\"/var/lib/docker/overlay2/fe367cc697a94e768b966c7c750a5611cde1c1461ceb2ec091590d0bc178f59a/merged\\\" at \\\"/var/lib/docker/overlay2/fe367cc697a94e768b966c7c750a5611cde1c1461ceb2ec091590d0bc178f59a/merged/usr/local/tomcat/webapps/atlas/js/config-local.js\\\" caused \\\"not a directory\\\"\"": unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type
ERROR: Encountered errors while bringing up the project.

Appears the sub-directory "merged" is missing. Here is the contents of the parent directory (after an abend because of the above error):

rm@rm-desktop:~/dev/ohdsi$ sudo ls -l /var/lib/docker/overlay2/fe367cc697a94e768b966c7c750a5611cde1c1461ceb2ec091590d0bc178f59a/merged
ls: cannot access '/var/lib/docker/overlay2/fe367cc697a94e768b966c7c750a5611cde1c1461ceb2ec091590d0bc178f59a/merged': No such file or directory
rm@rm-desktop:~/dev/ohdsi$ sudo ls -l /var/lib/docker/overlay2/fe367cc697a94e768b966c7c750a5611cde1c1461ceb2ec091590d0bc178f59a/
total 16
drwxr-xr-x 2 root root 4096 Aug 10 21:55 diff
-rw-r--r-- 1 root root   26 Aug 10 21:55 link
-rw-r--r-- 1 root root  753 Aug 10 21:55 lower
drwx------ 3 root root 4096 Aug 10 21:55 work

Appreciate any guidance on fixing this error. Thank you!

**Comment by leeevans** [comment]
it seems to be an issue with the way the config-local.js mount path is being specified. Ensure you specify the full path and file name of the file on the host and the full path and file name of the file as you want it to appear inside the docker container.
