### ISSUE TITLE
Documentation about environment variables

### ISSUE THREAD

**Issue by sdebruyn** [OHDSI/Broadsea#24]
The difference between the datasource and the flyway_datasource configuration properties is not clear. My CDM DB is in Azure SQL Database and the WebAPI DB is on a PostgreSQL server.

What does `env=webapi-postgresql` refer to? The OMOP or the WebAPI DB?
What do the `datasource.` properties refer to? I thought it was WebAPI, but one of the properties is `datasource.cdm.schema` which seems to refer to the CDM DB, while that config is in the source/daimon tables.

**Comment by leeevans** [comment]
webapi-postgresql is a java mvn profile. See WebAPI pom.xml here:
https://github.com/OHDSI/WebAPI/blob/master/pom.xml

Flyway is used to automatically manage database migrations for the OHDSI (atlas/webapi application database - your WebAPI DB).

https://flywaydb.org/
