### ISSUE TITLE
Env vars should not contain dots

### ISSUE THREAD

**Issue by sdebruyn** [OHDSI/Broadsea#25]
Bash manual says: `name   A word consisting only of alphanumeric characters and underscores, and beginning with an alphabetic character or an underscore.  Also referred to as an identifier.`

**Comment by leeevans** [comment]
These are overrides for java Spring application configuration properties:
https://docs.spring.io/spring-boot/docs/1.2.0.M1/reference/html/howto-properties-and-configuration.html
