### ISSUE TITLE
CORS errors in Atlas

### ISSUE THREAD

**Issue by fnwirth** [OHDSI/Broadsea#27]
Dear broadsea team,

I used broadsea to create an OHDSI environment and with Chrome I can not open Atlas since [CORS errors ](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS/Errors) are displayed in the console. When I start Chrome with CORS deactivated it works.

**Comment by leeevans** [comment]
Add the below line to the docker-compose.yml section in order to disable CORS security checks:

      - security_origin=*
