### ISSUE TITLE
SQL Server yml-error

### ISSUE THREAD

**Issue by OskarGauffin** [OHDSI/Broadsea#28]
Hello! 

Thanks for putting this piece of software together. 

I'm struggling following the setup-instructions on broadsea, and I have two sets of questions:

A) I'm a bit confused about some of the requested information in the yml-file, when attempting to connect broadsea to a remote sql server instance (where my Omop-data lies). The instruction says:

"specify the database connection info for your database [...]

database name
database schema name
database table prefix
database user name
database user password"

I have a database name, a schema name, a user name and password for access to the remote server, but no table prefix, and I'm not sure how docker will find the remote server, as I'm not entering information about the server anywhere. Could you explain if I need a table prefix, and where to enter the name of the server (or the IP, or whatever is needed). 

B) I've found some rows in the sql server yml which seems to be where I'm supposed to enter this information. The question here is that I'm not sure which one I should replace with the schema of my OmopCdm data source, it is the datasource.cdm.schema or the datasource.ohdsi.schema? Also, should my credentials be sorrounded by some quotation marks, or are they just entered as they are?

If I try and fill in these things as best as I can, I get the following error when running the "docker-compose up -d"-command in terminal:

```
ERROR: yaml.scanner.ScannerError: mapping values are not allowed here
  in ".\docker-compose.yml", line 93, column 65
```

I don't see anything that I should fill in or change on line 93, but perhaps the error message is misleading, and will be solved if I get the database information correct. 

I understand that it's a lot of work maintaning documentation, but if there is time, I think these details could be helpful additions to any set-up-documentation of broadsea. 

Thanks for any answers. : )

**Comment by leeevans** [comment]
@OskarGauffin There is a SQL Server specific version of the docker-compose.yml file here which may be helpful:
https://github.com/OHDSI/Broadsea/blob/master/sqlserver/docker-compose.yml

**Comment by OskarGauffin** [comment]
Thanks for trying to help Lee, that is the file I referred to when I wrote "sql server yml", sorry if that was unclear.

**Comment by leeevans** [comment]
OK, in that docker-compose.yml file there is an example of the jdbc string needed for the sql server database connection:

datasource.url=jdbc:sqlserver://192.168.99.100;databasename=secret-database-name

No quotes are needed around the jdbc string.

In the above example 192.168.99.100 is the IP address of the database server, so you should replace that with the IP address or DNS name of your database host server. Also replace 'secret-database-name' in that example with your sql server database name. It should default to using port 1433 for the database connection.

The default schema prefix for sql server databases is 'dbo'.
