### ISSUE TITLE
RStudio for Multiple User using Broadsea implementation

### ISSUE THREAD

**Issue by aykumarjha** [OHDSI/Broadsea#33]
Hi Team. I have configured RStudio using the broadsea implementation. I have below 2 queries:
1) How can we create multiple users for RStudio (currently there is only one with username: rstudio and default password : rstudio)
2) How can we setup user authentication for RStudio (LDAP, OAuth or using something similar to basic security configuration)

**Comment by leeevans** [comment]
These are typically considered Enterprise integration deployment requirements. If you would like commercial (paid) services to implement these requirements in your organization you can contact me at [ltscomputingllc.com](https:ltscomputingllc.com)
