### ISSUE TITLE
Refresh WebAPI cache in ATLAS

### ISSUE THREAD

**Issue by pradeepvuduthala** [OHDSI/Broadsea#35]
We have deployed ATLAS on the AWS platform and over the last few days, we updated the source and source daemon schemas to reflect the latest data cut.

However, we have noticed that the patient counts do not reflect the latest data-cut but the previous one.
I tried to use the refreshAtlasSources function from the CdmAtlasCutover package but it throws the following error:

refreshAtlasSources('https://ohdsi-sb-us.enterprise.com:443/WebAPI')
Base URL not valid, should be like http://api.ohdsi.org:80/WebAPI

I was wondering if there is an alternative way to refresh the WebAPI cache?

We have tried below commands to restart the WEBAPI server but issue did not resolve and we are using your docker file for atlas deployment.
docker stop postgresql_broadsea-webtools_1
docker start postgresql_broadsea-webtools_1
Also, the refresh button in the ATLAS configuration tab fails to run.
I would be grateful if you could provide any advice on how to tackle these issues?

**Comment by shailender1984** [comment]
HI Lee Evans,
Please have a look on this issue and suggest earliest.

**Comment by shailender1984** [comment]
HI Lee Evans,
Please have a look on this issue and suggest earliest.

**Comment by leeevans** [comment]
You can open the "/WebAPI/sources/refresh" endpoint in a browser (prefix that path with your atlas WebAPI installation url) to make Atlas read the source and source_daimon changes, as an alternative to restarting the Docker container. Note. It will fail with a 'not authorized' error if you have Atlas security enabled and call it without a valid Atlas session token.

Review the logs to see if there are any error messages related to (re)-generating cache on Atlas startup. It also can take some time to build the cache on Atlas startup depending on how much data you have loaded - maybe up to 20 minutes?)

**Comment by leeevans** [comment]
It's difficult to diagnose specific Atlas installation issues without direct access to your system.  

What error messages are you seeing in the logs?

See the troubleshooting section here, for info on how to view the logs:
https://github.com/OHDSI/Broadsea#troubleshooting

**Comment by shailender1984** [comment]
Hi Lee
Many thanks for your response !!!
I will check with user "roumpans" and confirm.
