### ISSUE TITLE
Getting http 401 error while accessing the URL : https://ohdsi-sb-us.apollo.roche.com:443/WebAPI/source/sources

### ISSUE THREAD

**Issue by pradeepvuduthala** [OHDSI/Broadsea#36]
Hi Lee,

We are not able to access the data source after configuration inside the OHDSI tool.
We are using docker Atlas image while we are accessing the below WEBAPI we are not able to access it.
Please let us know whether we need to do any configuration changes on the docker image or docker compose file.

WEBAPI URL : ![Error screenshot](https://user-images.githubusercontent.com/108405454/188632550-79d6a7d3-56a2-40d6-a426-3e96a0c48398.PNG)

**Comment by pradeepvuduthala** [comment]
Hi Lee,

Please let us know if  you can help us on this issue using consulting services from your side.
I will involve my team on this and we can resolve this issue.
We will be waiting to hear back from you on this.

Thankyou.

**Comment by pradeepvuduthala** [comment]
Hi Lee,

Please provide your email address so that my team will reach you out for the consulting.

Thankyou.

**Comment by leeevans** [comment]
Hi Pradeep,

You can reach me for consulting engagements here:

http://www.ltscomputingllc.com/contact-us/

**Comment by pradeepvuduthala** [comment]
Hi Lee,

I have filled the above form with the details.

Regards,
Pradeep V
Consultant - PHC Informatics
E-Mail: ***@***.***
Group E-mail: ***@***.***
