### ISSUE TITLE
Missing OHDSI tables

### ISSUE THREAD

**Issue by David-N-Perkins** [OHDSI/Broadsea#37]
I'm trying to get a Broadsea up and running using PostreSQL, but I keep getting errors in Atlas that tables are missing.

## Setup
I modified `postgresql/docker-compose.yml` to include a PostgreSQL service:
```
  postgres:
    image: postgres
    ports: 5432:5432
    environment:
      POSTGRES_PASSWORD: testpass
```
And updated the jdbc, username, & password fields for `broadsea-webtools`.

Then I ran `docker-compose up`, and loaded the synpuf 5% data into PostgreSQL using these [scripts](https://github.com/OHDSI/CommonDataModel/tree/v5.2.2/PostgreSQL).

Updated and ran `source_source_daimon.sql` on PostgreSQL.

Next, restarted the broadsea-webtools and broadsea-methods-library containers. 

## Errors
The Atlas UI loaded fine. It showed the new source I loaded. Then I tried defining a very simple cohort and tried to generate it, but got this error:
```
org.springframework.jdbc.BadSqlGrammarException: StatementCallback; bad SQL grammar [DELETE FROM ohdsi.cohort_cache WHERE design_hash = 1763856560; DELETE FROM ohdsi.cohort_inclusion_result_cache WHERE design_hash = 1763856560; DELETE FROM ohdsi.cohort_inclusion_stats_cache WHERE design_hash = 1763856560; DELETE FROM ohdsi.cohort_summary_stats_cache WHERE design_hash = 1763856560; DELETE FROM ohdsi.cohort_censor_stats_cache WHERE design_hash = 1763856560]; nested exception is org.postgresql.util.PSQLException: ERROR: relation "ohdsi.cohort_cache" does not exist
  Position: 13
 ```
I also checked the `broadsea-webtools` logs and found that error and this one: `PSQLException: ERROR: relation "ohdsi.achilles_analysis" does not exist`.

It appears that some of the OHDSI tables were not created, but I couldn't find any related errors. I attached my updated [docker-compose.txt](https://github.com/OHDSI/Broadsea/files/9648851/docker-compose.txt) (I had to change the extension to upload the file) and [stdout.log](https://github.com/OHDSI/Broadsea/files/9648825/stdout.log).

**Comment by David-N-Perkins** [comment]
I realized I missed this step
>Run the OHDSI Achilles R package to populate the Atlas reports Achilles statistics database tables

But I can't login into RStudio. I tried rstudio/rstudio and rstudio/mypass, but keep getting invalid username/password.

**Comment by ahungele** [comment]
We are getting the same error message when we try to create a cohort in Atlas.

Our PostgreSQL database is directly installed in a VM (Ubuntu 20.04 LTS). We installed Atlas using the Broadsea container.  
We already ran Achilles directly in the VM using the following script. 

```
source('./scripts/connect-db.r')

analysis_not_implemented <- c()
analysis <- Achilles::getAnalysisDetails()$ANALYSIS_ID
analysis <- analysis[!analysis %in% analysis_not_implemented]

skipTests <- c(424,624,824,1815,1824)

Achilles::achilles(
  connectionDetails=cd,
  cdmDatabaseSchema="cdm",
  vocabDatabaseSchema="cdm",
  resultsDatabaseSchema="cdm_results",
  scratchDatabaseSchema="cdm_scratch",
  sourceName="source",
  cdmVersion="5.4",
  numThreads=1,
  analysisIds=analysis,
  excludeAnalysisIds=skipTests
)

Achilles::exportToJson(
  connectionDetails=cd,
  cdmDatabaseSchema="cdm",
  resultsDatabaseSchema="cdm_results",
  outputPath="outputs/achilles-web/data"
)
```

Using rstudio/mypass I am able to login into RStudio hosted in the Broadsea container.

**Comment by tiagotaveiragomes** [comment]
Would it be possible to share the Dockerfile that was used to generate the image mentioned in the docker-compose.yml? We would really like to have a go at updating in to work against WebAPI and ATLAS 12 that was just released a few days ago 😊 Then we can suggest make a MR if we are successful!
Thank you so much!

**Comment by David-N-Perkins** [comment]
All the containers in the docker-compose.yml file are public images. I didn't create any of them. 

I was able to get things working by hitting the `WebAPI/ddl/results` endpoint and using that to create all the missing tables. I wasn't ever able to login to RStudio.

**Comment by ahungele** [comment]
Thank you, that helped a lot!
