### ISSUE TITLE
Document access to logs

### ISSUE THREAD

**Issue by ajmazurie** [OHDSI/Broadsea#4]
I have a working PostgreSQL instance with a CDMv5 database in it. I confirm that I can access this database on the command line using `psql`, which reads various environment variables I set (`PGHOST`, `PGDATABASE`, `PGUSER` and `PGPASSWORD`).

I have a script that generates the `docker-compose.yml` and `source_source_daimon.sql` by using a template where the various key variables are replaced by the environment variables above. The script is available at https://gist.github.com/ajmazurie/1ff080a4dcbee815b21076fc43d883ef

Despite using the same environment variables I get a "unable to connect to an instance of the webapi. please contact your administrator to resolve this issue." error message. I'd like to dig more into it, but I couldn't find any log file telling me what happened in the running container. Nothing in `/usr/local/tomcat/logs/` gave me a hint.

Is there a way to tell what happened, and fix the connection issue?
Best, Aurélien

**Comment by leeevans** [comment]
I've now documented how to view the logs in a new "Troubleshooting" section of the README.md file
