### ISSUE TITLE
Cannot connect to Rstudio Server on Mac

### ISSUE THREAD

**Issue by nadavrap** [OHDSI/Broadsea#42]
Hi,
I cloned the repo and run the docker. The ATLAS seems to work, as I can open it and generate cohorts. However, when I open the Rstudio Server, after signing in I get the next error:

> Cannot Connect to R Session
> Could not connect to the R session on RStudio Server.
> 
> Unable to connect to service (1)
![image](https://user-images.githubusercontent.com/12637950/206150324-3bf434bc-f863-4b02-965e-0e6decfdc4c2.png)

**Comment by nadavrap** [comment]
Oh, now I see that there was already such an issue #40 that was closed without resolution.

**Comment by leeevans** [comment]
@nadavrap The resolution to #40 was that we don't currently support a (non-intel) M1 / M2 Mac  for running the RStudio Docker image (broadsea-hades).

Are you using an M1 / M2 Mac?  If not, are there any specific error messages in the broadsea-hades Docker container log?

You can view that log with this command:
`docker logs broadsea-hades`

**Comment by nadavrap** [comment]
Indeed, I use a non-Intel Mac.

**Comment by natb1** [comment]
@nadavrap I haven't tested this, but often with docker on silicon you can try this before running your docker commands `export DOCKER_DEFAULT_PLATFORM=linux/amd64`

**Comment by nadavrap** [comment]
@natb1, it didn't work. I still get the same error.
