### ISSUE TITLE
Using modified config-local.js in Atlas

### ISSUE THREAD

**Issue by alondhe** [OHDSI/Broadsea#43]
With the recent release of Broadsea, the overall docker compose file does not allow for passing in a modified config-local.js file for Atlas, it simply uses the one from the Atlas docker hub image.

**Comment by alondhe** [comment]
In my instance, I have edited my ohdsi-atlas service with this to get my config-local.js into the container:

```
volumes:
      - ./config-local.js:/tmp/config-local.js:ro
environment:
      CONFIG_PATH: "/tmp/config-local.js"
```

**Comment by acumenus** [comment]
You are referring to adding those to your docker-compose.yaml, correct? 

Would this be necessary to get traefik to run properly on a VM?

![Screenshot 2023-03-09 at 3 35 35 PM](https://user-images.githubusercontent.com/126921002/224155914-057c9098-4ea1-437b-ba8f-687fe0dee273.png)

**Comment by alondhe** [comment]
No, this is for the purpose of changing the config-local file for Atlas. The one in the docker hub image doesn't have a lot of options enabled, such as security.

I think we can handle this via a new ohdsi-atlas service entry and a profile for it.

**Comment by jtheobaldhp** [comment]
By the way, to fix the error screenshotted above, @acumenus 

- change `ports` in traefik from `${BROADSEA_HOST}:80:80` to just `80:80`. 
- update BROADSEA_HOST to ip address of host machine. Can keep 127.0.0.1 if running locally, or in my case, I set it to an elastic IP directed to an AWS EC2 instance running the docker containers.
