### ISSUE TITLE
Error from Atlas: "Unable to connect to an instance of the WebAPI"

### ISSUE THREAD

**Issue by ajmazurie** [OHDSI/Broadsea#5]
Hi,
Thanks to the help I got in https://github.com/OHDSI/Broadsea/issues/4 I was able to dig further into the "unable to connect to an instance of the webapi. please contact your administrator to resolve this issue." error message.

The whole log I found in the `ohdsi/broadsea-webtools` container is available at http://pastebin.com/mTGesfzN, but the relevant message (I think?) is this one: `java.lang.ClassNotFoundException: "org.postgresql.Driver"`.

I thought the PostgreSQL JDBC driver was included in the Docker image already; am I missing something?

Best, Aurélien

**Comment by leeevans** [comment]
Yes, that looks like the issue which is odd because the driver should be included in the Docker image.

Can you check that the file postgresql-9.4-1201-jdbc41.jar is in the following directory in the running docker container?
/usr/local/tomcat/webapps/WebAPI/WEB-INF/lib

If that driver jar file is in that directory then the issue may be related to your docker-compose.yml file so please post it here (remove any passwords or ip addresses etc) and I'll take a look.

Thanks

**Comment by ajmazurie** [comment]
I confirm that `postgresql-9.4-1201-jdbc41.jar` is in `/usr/local/tomcat/webapps/WebAPI/WEB-INF/lib/`; just to be sure, the MD5 sum is `a707b13c0c067a707d41db09dc0b3342`.

The script I wrote to generate the `docker-compose.yml` file is here: https://gist.github.com/ajmazurie/1ff080a4dcbee815b21076fc43d883ef

**Comment by leeevans** [comment]
OK, try removing the double quotes in your script.  

e.g.  Use:

- datasource.driverClassName=org.postgresql.Driver

Instead of:

- datasource.driverClassName="org.postgresql.Driver"

You may need to make that change for the other script vars too.

**Comment by ajmazurie** [comment]
Thanks! I've been able to make some progress by applying your fix. I still get the `unable to connect to an instance of the webapi. please contact your administrator to resolve this issue` error message from Atlas but this time the supervisor log has a different content: http://pastebin.com/S3DrN4dF

What's interesting is that when logging to the PostgreSQL server in parallel (using `psql`) I confirm that my metadata schema (not `ohdsi` in this case, but `synpuf5_broadsea`) is created as well as tables: 

```
                                              List of relations
+------------------+----------------------------------------+----------+----------+------------+-------------+
|      Schema      |                  Name                  |   Type   |  Owner   |    Size    | Description |
+------------------+----------------------------------------+----------+----------+------------+-------------+
| synpuf5_broadsea | batch_job_execution                    | table    | amazurie | 8192 bytes |             |
| synpuf5_broadsea | batch_job_execution_context            | table    | amazurie | 8192 bytes |             |
| synpuf5_broadsea | batch_job_execution_params             | table    | amazurie | 0 bytes    |             |
| synpuf5_broadsea | batch_job_execution_seq                | sequence | amazurie | 8192 bytes |             |
| synpuf5_broadsea | batch_job_instance                     | table    | amazurie | 0 bytes    |             |
| synpuf5_broadsea | batch_job_seq                          | sequence | amazurie | 8192 bytes |             |
| synpuf5_broadsea | batch_step_execution                   | table    | amazurie | 8192 bytes |             |
| synpuf5_broadsea | batch_step_execution_context           | table    | amazurie | 8192 bytes |             |
| synpuf5_broadsea | batch_step_execution_seq               | sequence | amazurie | 8192 bytes |             |
| synpuf5_broadsea | cca                                    | table    | amazurie | 0 bytes    |             |
| synpuf5_broadsea | cca_execution                          | table    | amazurie | 0 bytes    |             |
| synpuf5_broadsea | cohort                                 | table    | amazurie | 0 bytes    |             |
| synpuf5_broadsea | cohort_concept_map                     | table    | amazurie | 0 bytes    |             |
| synpuf5_broadsea | cohort_definition                      | table    | amazurie | 8192 bytes |             |
| synpuf5_broadsea | cohort_definition_details              | table    | amazurie | 8192 bytes |             |
| synpuf5_broadsea | cohort_generation_info                 | table    | amazurie | 0 bytes    |             |
| synpuf5_broadsea | cohort_inclusion                       | table    | amazurie | 8192 bytes |             |
| synpuf5_broadsea | cohort_inclusion_result                | table    | amazurie | 0 bytes    |             |
| synpuf5_broadsea | cohort_inclusion_stats                 | table    | amazurie | 0 bytes    |             |
| synpuf5_broadsea | cohort_study                           | table    | amazurie | 16 kB      |             |
| synpuf5_broadsea | cohort_study_cohort_study_id_seq       | sequence | amazurie | 8192 bytes |             |
| synpuf5_broadsea | cohort_summary_stats                   | table    | amazurie | 0 bytes    |             |
| synpuf5_broadsea | concept_of_interest                    | table    | amazurie | 8192 bytes |             |
| synpuf5_broadsea | concept_of_interest_id_seq             | sequence | amazurie | 8192 bytes |             |
| synpuf5_broadsea | concept_set                            | table    | amazurie | 0 bytes    |             |
| synpuf5_broadsea | concept_set_generation_info            | table    | amazurie | 0 bytes    |             |
| synpuf5_broadsea | concept_set_item                       | table    | amazurie | 0 bytes    |             |
| synpuf5_broadsea | concept_set_item_sequence              | sequence | amazurie | 8192 bytes |             |
| synpuf5_broadsea | concept_set_negative_controls          | table    | amazurie | 8192 bytes |             |
| synpuf5_broadsea | concept_set_negative_controls_sequence | sequence | amazurie | 8192 bytes |             |
| synpuf5_broadsea | concept_set_sequence                   | sequence | amazurie | 8192 bytes |             |
| synpuf5_broadsea | drug_hoi_evidence                      | table    | amazurie | 8192 bytes |             |
| synpuf5_broadsea | drug_hoi_evidence_sequence             | sequence | amazurie | 8192 bytes |             |
| synpuf5_broadsea | drug_hoi_relationship                  | table    | amazurie | 8192 bytes |             |
| synpuf5_broadsea | drug_labels                            | table    | amazurie | 648 kB     |             |
| synpuf5_broadsea | evidence_sources                       | table    | amazurie | 8192 bytes |             |
| synpuf5_broadsea | evidence_sources_sequence              | sequence | amazurie | 8192 bytes |             |
| synpuf5_broadsea | exampleapp_widget                      | table    | amazurie | 0 bytes    |             |
| synpuf5_broadsea | feas_study_generation_info             | table    | amazurie | 0 bytes    |             |
| synpuf5_broadsea | feas_study_inclusion_stats             | table    | amazurie | 0 bytes    |             |
| synpuf5_broadsea | feas_study_index_stats                 | table    | amazurie | 0 bytes    |             |
| synpuf5_broadsea | feas_study_result                      | table    | amazurie | 0 bytes    |             |
| synpuf5_broadsea | feasibility_inclusion                  | table    | amazurie | 8192 bytes |             |
| synpuf5_broadsea | feasibility_study                      | table    | amazurie | 8192 bytes |             |
| synpuf5_broadsea | heracles_analysis                      | table    | amazurie | 64 kB      |             |
| synpuf5_broadsea | heracles_heel_results                  | table    | amazurie | 0 bytes    |             |
| synpuf5_broadsea | heracles_results                       | table    | amazurie | 8192 bytes |             |
| synpuf5_broadsea | heracles_results_dist                  | table    | amazurie | 8192 bytes |             |
| synpuf5_broadsea | heracles_visualization_data            | table    | amazurie | 8192 bytes |             |
| synpuf5_broadsea | heracles_viz_data_sequence             | sequence | amazurie | 8192 bytes |             |
| synpuf5_broadsea | hibernate_sequence                     | sequence | amazurie | 8192 bytes |             |
| synpuf5_broadsea | ir_analysis                            | table    | amazurie | 8192 bytes |             |
| synpuf5_broadsea | ir_analysis_details                    | table    | amazurie | 8192 bytes |             |
| synpuf5_broadsea | ir_analysis_result                     | table    | amazurie | 0 bytes    |             |
| synpuf5_broadsea | ir_analysis_strata_stats               | table    | amazurie | 0 bytes    |             |
| synpuf5_broadsea | ir_execution                           | table    | amazurie | 8192 bytes |             |
| synpuf5_broadsea | ir_strata                              | table    | amazurie | 8192 bytes |             |
| synpuf5_broadsea | laertes_summary                        | table    | amazurie | 8192 bytes |             |
| synpuf5_broadsea | laertes_summary_sequence               | sequence | amazurie | 8192 bytes |             |
| synpuf5_broadsea | penelope_laertes_uni_pivot             | table    | amazurie | 8192 bytes |             |
| synpuf5_broadsea | penelope_laertes_universe              | table    | amazurie | 8192 bytes |             |
| synpuf5_broadsea | schema_version                         | table    | amazurie | 16 kB      |             |
| synpuf5_broadsea | source                                 | table    | amazurie | 8192 bytes |             |
| synpuf5_broadsea | source_daimon                          | table    | amazurie | 0 bytes    |             |
+------------------+----------------------------------------+----------+----------+------------+-------------+
(64 rows)
```

As you can see however these tables are all empty, except for `schema_version` which shows multiple operations being successfully performed (as shown by a value of `t` in the `success` column).

My understanding is that something within Broadsea is able to not only access the PostgreSQL database server, but also modify it. What I don't understand is why it fails to go further, and allow Atlas for example to access it.

Any suggestion? Best, Aurélien

**Comment by leeevans** [comment]
It looks like you're making good progress.

The flyway framework called by the OHDSI WebAPI is applying the database migration scripts correctly.

Now the next activity would be for you to populate the source and source_daimon tables with your database connection and schema info and then perform a docker stop and docker start of the container so that WebAPI reads the configuration info from those two tables.

See the "Quick Start Broadsea Deployment" section at the link below for more info on those steps:
https://github.com/OHDSI/Broadsea

The repo has some example SQL scripts you can edit to populate those two tables.

**Comment by ajmazurie** [comment]
I agree, the population of the `source` and `source_daimon` is what seems not to work right now. I'm not sure why exactly; the `source_source_daimon.sql` file my script generates should have everything set up as needed:

```
-- remove any previously added database connection configuration data
TRUNCATE synpuf5_broadsea.source;
TRUNCATE synpuf5_broadsea.source_daimon;

-- OHDSI CDM source
INSERT INTO synpuf5_broadsea.source(
                source_id,
                source_name,
                source_key,
                source_connection,
                source_dialect)
     VALUES (1, 'OHDSI CDM V5 Database', 'OHDSI-CDMV5',
                'jdbc:postgresql://SERVER:5432/DATABASE?user=USER&password=PASSWORD',
                'postgresql');

-- CDM daimon
INSERT INTO synpuf5_broadsea.source_daimon(
                source_daimon_id,
                source_id,
                daimon_type,
                table_qualifier,
                priority)
     VALUES (1, 1, 0, 'synpuf5', 2);

-- VOCABULARY daimon
INSERT INTO synpuf5_broadsea.source_daimon(
                source_daimon_id,
                source_id,
                daimon_type,
                table_qualifier,
                priority)
     VALUES (2, 1, 1, 'synpuf5', 2);

-- RESULTS daimon
INSERT INTO synpuf5_broadsea.source_daimon(
                source_daimon_id,
                source_id,
                daimon_type,
                table_qualifier,
                priority)
     VALUES (3, 1, 2, 'ohdsi', 2);

-- EVIDENCE daimon
INSERT INTO synpuf5_broadsea.source_daimon(
                source_daimon_id,
                source_id,
                daimon_type,
                table_qualifier,
                priority)
     VALUES (4, 1, 3, 'ohdsi', 2);
```

It may be that the values I put in the `table_qualifier` column are incorrect, but I couldn't find any documentation on it. For information, in our system we want Broadsea to use `synpuf5_broadsea` as its metadata database and `synpuf5` as the CDMv5 database.

**Comment by leeevans** [comment]
@ajmazurie The documentation is here:
http://www.ohdsi.org/web/wiki/doku.php?id=documentation:software:webapi:source_configuration

For postgreSQL the table_qualifer should be the schema name.

Try replacing 'ohdsi' with  'synpuf5_broadsea' in the source_daimon table and docker stop, docker start your container.

**Comment by ajmazurie** [comment]
Ah! I didn't know the `source` and `source_daimon` were part of the OHDSI stack itself; for some reasons I thought it was an artifact of **Broadsea**.

**Comment by ajmazurie** [comment]
The fix you suggested doesn't appear to do much, unfortunately. **Broadsea** behaves as is the `source_source_daimon.sql` wasn't there (or was ignored). Is there a way to confirm this file is used?

**Comment by t-abdul-basser** [comment]
Please try http://192.168.99.100:8080/WebApi/source/refresh and confirm that the schema(s) for the data sources are what you would expect.

Get Outlook for Android<https://aka.ms/ghei36>



On Wed, Oct 26, 2016 at 7:04 PM -0400, "Aurélien Mazurie, Ph.D." <notifications@github.com<mailto:notifications@github.com>> wrote:


The fix you suggested doesn't appear to do much, unfortunately. Broadsea behaves as is the source_source_daimon.sql wasn't there (or was ignored). Is there a way to confirm this file is used?

**Comment by leeevans** [comment]
Here are a couple of things to check:

   - Did you successfully execute the SQL file in your postgreSQL client?
   Broadsea doesn't do anything with the SQL file. It's just an example of the
   SQL statements you would use to manually populate the two tables.
   - Did you do a docker stop and docker start on your Broadsea container
   after you executed the SQL file?  The OHDSI WebAPI inside the Broadsea
   container only queries the source and source_daimon tables on startup.

**Comment by chrisknoll** [comment]
Just want to add to @leeevans post, there is a WebAPI url that will refresh the source/source_daimon tables in the WebAPI cache that @t-abdul-basser gave:

/WebAPI/source/refresh

The only correction i'd make to @t-abdul-basser is that I believe that the path is case sensitive, so WebAPI needs to be cased like so.

**Comment by t-abdul-basser** [comment]
@chrisknoll Thanks for the catch: it is case sensitive.  Corrected in original comment.

**Comment by ajmazurie** [comment]
Thanks for your help! Manually running the `source_source_daimon.sql` did the trick. I misread the document; I thought this file was automatically imported by **Broadsea**.

**Comment by leeevans** [comment]
Excellent!  I'll go ahead and close this issue now.

**Comment by shubham318** [comment]
Hi, My name is Shubham
I am working on OHDSI tools installation on my local machine, I start work on it from the last two weeks.
For now, What I did is, installed Postgre on my local and using webapi created schema for CDM.
because of port 8080 is used by tomcat, I run the broadsea on GCP VM instance. 
After completing all the steps I get following errors:

![image](https://user-images.githubusercontent.com/36188450/82884350-3cdd4680-9f61-11ea-83e8-bc6358dd627d.png)

My postgre schema after running webapi looks like below:

![image](https://user-images.githubusercontent.com/36188450/82884606-8f1e6780-9f61-11ea-8432-fcbc3dd3716b.png)

My Broadsea docker-compose.yaml file looks like this:

version: '2'

services:

  broadsea-methods-library:
    image: ohdsi/broadsea-methodslibrary
    ports:
      - "8787:8787"
      - "6311:6311"
    environment:
      - PASSWORD=mypass

  broadsea-webtools:
    image: ohdsi/broadsea-webtools
    ports:
      - "8080:8080"
    volumes:
     - .:/tmp/drivers/:ro
     - ./config-local.js:/usr/local/tomcat/webapps/atlas/js/config-local.js:ro
    environment:
      - WEBAPI_URL=http://{local machine Ip address where postgre is installed}:63421
      - env=webapi-postgresql
      - datasource_driverClassName=org.postgresql.Driver
      - datasource_url=jdbc:postgresql:// database:5432/ohdsi
      - datasource.cdm.schema=cdm
      - datasource.ohdsi.schema=ohdsi
      - datasource_username=ohdsi_admin_user
      - datasource_password=admin1
      - spring.jpa.properties.hibernate.default_schema=ohdsi
      - spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
      - spring.batch.repository.tableprefix=ohdsi.BATCH_
      - flyway_datasource_driverClassName=org.postgresql.Driver
      - flyway_datasource_url=jdbc:=jdbc:postgresql://database:5432/ohdsi
      - flyway_schemas=ohdsi
      - flyway.placeholders.ohdsiSchema=ohdsi
      - flyway_datasource_username=ohdsi_admin_user
      - flyway_datasource_password=admin1
      - flyway.locations=classpath:db/migration/postgresql
