### ISSUE TITLE
Errors on startup on Windows

### ISSUE THREAD

**Issue by greshje** [OHDSI/Broadsea#67]
I'm getting the errors shown below.  

**Using:**
git clone https://github.com/OHDSI/Broadsea.git
cd Broadsea
docker compose pull && docker-compose --profile default up -d

**Errors:**
![image](https://user-images.githubusercontent.com/36824929/233424366-ddb20126-239d-4fbb-aff6-351ba6ca560c.png)

**content**
![image](https://user-images.githubusercontent.com/36824929/233424558-3ce9c433-17d4-4c3b-a83b-c7691febd107.png)

**atlas**
![image](https://user-images.githubusercontent.com/36824929/233424701-9dc6b78d-08a2-4915-8ca5-91fb8a1bbbd0.png)

**Comment by sudoshi** [comment]
This looks like a port conflict.  Can you check if you have any other web server running?  Like IIS?

**Comment by alondhe** [comment]
Turns out it's line endings. I've pushed fixes to the issue-67 branch

**Comment by leeevans** [comment]
Issue-67 branch merged via pull request
