### ISSUE TITLE
SQL Server jar missing in image

### ISSUE THREAD

**Issue by cukarthik** [OHDSI/Broadsea#7]
I'm having issues connecting to a SQL Server instance. In the logs, I see this error message:

```
Caused by: java.lang.ClassNotFoundException: com.microsoft.sqlserver.jdbc.SQLServerDriver
```
It seems that the SQL Server jar is missing in  /usr/local/tomcat/webapps/WebAPI/WEB-INF/lib/

**Comment by leeevans** [comment]
Download the proprietary SQL Server jdbc driver jar from Microsoft and place it in the same directory as the Broadsea docker-compose.yml file. The Broadsea docker image should load it automatically when the container is run.

**Comment by cukarthik** [comment]
Ah. Would that be the same if I tried using the jTDS jar for MSSQL?

**Comment by leeevans** [comment]
I haven't tested it but It should work the same way for the jTDS.jar

**Comment by t-abdul-basser** [comment]
No you would have to copy that file over to the Tomcat directory (or a similar Java class path folder) yourself because the deploy script that copies the MS SQL Server JDBC jar searches for a file name pattern that will not find the JTDS jar file. Please correct me if I'm wrong @leeevans :)

Get Outlook for Android<https://aka.ms/ghei36>




On Tue, Feb 21, 2017 at 9:05 AM -0500, "cukarthik" <notifications@github.com<mailto:notifications@github.com>> wrote:


Ah. Would that be the same if I tried using the jTDS jar for MSSQL?

**Comment by leeevans** [comment]
Taha, thanks, you are correct.

I tried to make it generic but there is an assumption in the deploy script
that the driver contains the string 'jdbc' or 'JDBC' in the file name.

Manually renaming the jTDS.jar file in the same directory as
docker-compose.yml to jTDSjdbc.jar should work.

Lee

**Comment by cukarthik** [comment]
@leeevans where would the jar file get copied to? Would it be loaded to /usr/local/tomcat/webapps/WebAPI/WEB-INF/lib? I tried renaming my jtds.jar to jtds-jdbc.jar and couldn't find it at that location.

**Comment by leeevans** [comment]
@cukarthik it should be in /usr/local/tomcat/lib

**Comment by cukarthik** [comment]
Thanks. I see it.

Looking at the logs, I get the following error as well. 

```
Caused by: org.hibernate.HibernateException: Access to DialectResolutionInfo cannot be null when 'hibernate.dialect' not set
```

Is this a setting in the yml file that I need to make?

**Comment by leeevans** [comment]
@cukarthik that could be due to a database connection error.  The below example SQL Server docker-compose.yml file should work with relevant updates for your database connection:

https://github.com/OHDSI/Broadsea/blob/master/sqlserver/docker-compose.yml
