### ISSUE TITLE
Simplify ATLAS permissions interface

### ISSUE THREAD

**Issue by sudoshi** [OHDSI/Broadsea#72]
![Screenshot 2023-04-23 at 7 42 01 PM](https://user-images.githubusercontent.com/100962480/233881171-0c632bf5-5472-4986-8877-9f21f9117651.png)

Unless I am doing something wrong, it seems tedious to add permissions to a new role type in Atlas.  Perhaps a 'add all' one click at the top of the checkbox column would make this easier.

This is especially the case when you add a new data source (CDM), and permissions need to be replicated.

**Comment by alondhe** [comment]
This isn't part of scope here, it's an Atlas design. I'd recommend opening the issue there.
