### ISSUE TITLE
Basic Authentication doesn't seem to work.

### ISSUE THREAD

**Issue by cha-uth** [OHDSI/Broadsea#79]
Cannot login using the basic authentication

section 5 is set as followed:
SECURITY_AUTH_JDBC_ENABLED="true"
SECURITY_DB_DATASOURCE_SCHEMA="webapi_security"
SECURITY_DB_DATASOURCE_URL="jdbc:postgresql://broadsea-atlasdb:5432/postgres"
SECURITY_DB_DATASOURCE_DRIVERCLASSNAME="org.postgresql.Driver"
SECURITY_DB_DATASOURCE_USERNAME="postgres"
SECURITY_DB_DATASOURCE_PASSWORD="mypass"

Atlas (section4) Security provider is set to to "basic".

I add a new row of values for (email, password) in webapi_security.security table

**Comment by jtheobaldhp** [comment]
I too am struggling with this.

**Comment by alondhe** [comment]
Try reviewing this wiki: https://github.com/OHDSI/WebAPI/wiki/Basic-Security-Configuration#database

**Comment by cha-uth** [comment]
i did.  The webapi_security.security table is already created with two entries ('admin' and 'ohdsi').  Forgot to mention that I use the --profile default switch

**Comment by alondhe** [comment]
Okay good. I'll try to review tomorrow -- can't today/

**Comment by cha-uth** [comment]
I copied the /var/lib/ohdsi/webapi/WEB-INF/classes/application.properties from ohdsi-webapi container and it did not seem to have anything set from the .env file.  see attached

[application.zip](https://github.com/OHDSI/Broadsea/files/11401672/application.zip)

**Comment by alondhe** [comment]
That's expected. The env var file overrides that file during the WebAPI build.

**Comment by cha-uth** [comment]
I looked into webapi application.propterties and it looks like the query string is  "..select password from ohdsi.users_data.."
so I created a schema ohdsi and then a table users_data.  Populated with email and password.  And now the Atlas says it won't be able to connect to webapi.  The pertinent info in .env is
WEBAPI_SECURITY_PROVIDER="AtlasRegularSecurity"
# choose one, set it to enabled, and replace with appropriate values

# Basic
SECURITY_AUTH_JDBC_ENABLED="true"
SECURITY_DB_DATASOURCE_SCHEMA="ohdsi"
SECURITY_DB_DATASOURCE_URL="jdbc:postgresql://broadsea-atlasdb:5432/postgres"
SECURITY_DB_DATASOURCE_DRIVERCLASSNAME="org.postgresql.Driver"
SECURITY_DB_DATASOURCE_USERNAME="postgres"
SECURITY_DB_DATASOURCE_PASSWORD="mypass"

**Comment by cha-uth** [comment]
webapi is now working but when click on the "sign in" button and then select "basic". I got the HTTP 401 error

The link is https://<my atlas >/WebAPI/user/login/basic?redirectUrl=/home

**Comment by cha-uth** [comment]
correction, as it seems the text editor stripped out some characters.
The url is https://my_atlas_web/WebAPI/user/login/basic?redirectUrl=/home

**Comment by RomainTching** [comment]
Hi, I'm also having troubles setting up basic security. I get the result from the image below as soon as I click on ATLAS on the landing page. 
![atlas_security_setup_fail](https://github.com/OHDSI/Broadsea/assets/77339888/c1bf6a02-b5ab-4f2a-8104-4fbff90516b2)

My configuration settings are the same as @cha-uth mentions: `.env` file section 4 and 5 are filled similarly (I changed the password), and I also added my own entry to `webapi_security.security` table in addition to the two default rows. Any help would be very appreciated.

@cha-uth I don't quite understand your last few messages. Did you manage to make some progress by creating a duplicate of the `webapi_security` schema and calling it `ohdsi`?

**Comment by cha-uth** [comment]
@RomainTching - I think the codes called a schema called ohdsi.  So I created a schema called 'ohdsi' and puts username. password there.

**Comment by RomainTching** [comment]
> @RomainTching - I think the codes called a schema called ohdsi. So I created a schema called 'ohdsi' and puts username. password there.

Did this solve the issue for you? I tried but got the same error.

**Comment by cha-uth** [comment]
no.  The basic authentication doesn't work at all

**Comment by alondhe** [comment]
We're working on the basic auth. Regarding openldap, @cha-uth, are there any console errors in your browser after clicking login?

**Comment by cha-uth** [comment]
For openldap, there is no error in the browser. Just a blank page

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by cha-uth** [comment]
just FYI - I can browse the LDAP directory using my LDAP browser on port 1389

**Comment by alondhe** [comment]
From our installations we've tried, we haven't needed an entry for openldap in the traefik conf file, as we're not doing any web traffic routing with it. It simply needs to exist in the same docker network.

**Comment by alondhe** [comment]
Does your Atlas know to use LDAP (Section 4)?

**Comment by cha-uth** [comment]
Yes. I specifically set it for LDAP

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by alondhe** [comment]
Can you post your redacted env file?

**Comment by cha-uth** [comment]
I have re-cloned the develop git and it's pretty much un-changed mostly.  See attached

**Comment by alondhe** [comment]
I think replying via email doesn't allow attachments, can you try posting it in the thread directly?

**Comment by cha-uth** [comment]
here you go
[env.txt](https://github.com/OHDSI/Broadsea/files/11630140/env.txt)

**Comment by alondhe** [comment]
Can you also share the docker compose commands you used?

**Comment by cha-uth** [comment]
[.docker-compose.yml.txt](https://github.com/OHDSI/Broadsea/files/11635898/default.docker-compose.yml.txt)

**Comment by cha-uth** [comment]
I edited the docker-compose.yml to include "broadsea-openldap" for the "default" profile.  Just note that I can browse the ldap tree just fine after running the containers.  So it is running, when "docker-compose --profile default up -d" ran

**Comment by alondhe** [comment]
The text file didn't include your commands? 

To run the openldap container, you don't need to modify the yml file, you just need to run:
`docker-compose --profile openldap up -d`

For debugging's sake, let's keep the yml files as-is.

**Comment by cha-uth** [comment]
reverted the docker-compose.yml back to the original.
docker-compose --profile default up -d
docker-compose --profile openldap up -d

same result - a blank page after click on the login button --> select "ldap"

**Comment by cha-uth** [comment]
just FYI - the URI is http://127.0.0.1/WebAPI/user/login/ldap?redirectUrl=/home (BLANK page)

**Comment by alondhe** [comment]
that blank page is expected for that url, it's not designed to serve up anything. 

Can you open your chrome web console and go to "Network". When you click log in, what response is given by the below api call?

<img width="493" alt="image" src="https://github.com/OHDSI/Broadsea/assets/8037742/77ae8d2f-66bd-4b36-a28a-e5a646057747">

**Comment by cha-uth** [comment]
This is all I see
![ldap](https://github.com/OHDSI/Broadsea/assets/131785741/b5f04d0b-3213-4e2e-843d-ebc72c7c02c1)

**Comment by alondhe** [comment]
I think I missed these in my earlier review of your env, set these to true:

```
ATLAS_SECURITY_USE_FORM="true" # set to true for most security providers
ATLAS_SECURITY_USE_AJAX="true" # set to true for most security providers except CAS
```

**Comment by cha-uth** [comment]
Bingo!  It works on my local docker instance.  I will replicate it to a test server.

Thank you so much!

**Comment by alondhe** [comment]
Nice!
