### ISSUE TITLE
Spark driver not recognized

### ISSUE THREAD

**Issue by jtheobaldhp** [OHDSI/Broadsea#80]
Very grateful for the Broadsea 3.0 update and excited to dig in. Would really love more instructions around Spark and Databricks. It seems that `ohdsi-webapi` container doesn't register the Spark or Databricks drivers, despite placing in my root Broadsea directory. 

```
2023-05-03 17:31:39 ohdsi-webapi      | 2023-05-04 00:31:39.021 INFO localhost-startStop-1 org.ohdsi.webapi.DataAccessConfig - [] - error loading com.simba.spark.jdbc.Driver driver. com.simba.spark.jdbc.Driver
```

I have moved `SparkJDBC42.jar` from my download folder of `SimbaSparkJDBC42-2.6.22.1040` into my root Broadsea directory. I have similarly tried with a Databricks driver. 

Is there a naming convention that must be adopted for the driver to be registered?

**Comment by alondhe** [comment]
That won't add the JDBC file. Instead, you need to go to the ohdsi-webapi.yml file and add this to volumes. You can keep the name as SparkJDBC42.jar. 

```
volumes:
      - ./SparkJDBC42.jar:/var/lib/ohdsi/webapi/WEB-INF/lib/SparkJDBC42.jar
```

**Comment by jtheobaldhp** [comment]
Thank you. This worked!
