### ISSUE TITLE
Consider enabling db security provider by default

### ISSUE THREAD

**Issue by jtheobaldhp** [OHDSI/Broadsea#81]
* Pre-configuring DB security allows addition of data sources by admin user out of the box.
* Easier to disable default settings than enable by entering various connection strings.

**Comment by alondhe** [comment]
Interesting idea. We do have an openldap container in the works, that could be part of the "default" profile.

**Comment by jtheobaldhp** [comment]
Either one. Configuring security providers has been the most difficult part of setting up ATLAS.

**Comment by alondhe** [comment]
The develop branch now has the open ldap service, please take a look. It's not part of the "default" profile, so you'll need to deploy it using its profile of "openldap"
