### ISSUE TITLE
Authorization using LDAP ? 

### ISSUE THREAD

**Issue by gkowalski** [OHDSI/Broadsea#82]
Lets say we get ldap authentication working with WebAPI . Then what , if anything controls whom is authorized to Broadsea in general ? Anyone with in LDAP account can get in and poke around ? I've seen other apps that let one define a Group within LDAP that the user needs to be a memberOf to actually use that service . Don't see that or anything else in the settings for that. 

G

**Comment by alondhe** [comment]
That is up to your site. At ours, we have a group of authorized system admins that can log into the server and manage the docker engine and services. You could manage your docker group on the server to sync with a security group, but that is beyond the scope of Broadsea.

**Comment by alondhe** [comment]
Think I misread this. So you're asking about per service security? Aside from Atlas/WebAPI, which services do you have in mind?

**Comment by gkowalski** [comment]
Out of the box: 
If we were to use a local DB for authentication , we add users to it any they are then authorized to Atlas and can log into it. Great. Don't add a user and they can't log in. 

Once we set up LDAP Integration for our institution  within  the Webapi container , everyone in our institution could log into Atlas ( which we don't want ) . We want to control Authorization within ( or outside if need be) of ldap. We have other apps that use a separate LDAP Group membership , in this case we would call it BroadseaUsersGroup,  and add people as members to that group .Only at that point would they be able to see and use Atlas data , even if they successfully logged in with their corp credentials . 

G

**Comment by alondhe** [comment]
This seems like more of a site choice on how they want to architect their LDAP groups. You can then point to an LDAP group using the LDAP env variables. For instance, we use AD, but we created security groups that correspond to the various Atlas roles (Atlas users, specific data sources, moderator, etc).

**Comment by gkowalski** [comment]
Hmm , I didn't see where one can specify different LDAP Groups that correspond to the atlas  roles . Where is that documented ? Ass I see in the .env is SECURITY_AD_DEFAULT_IMPORT_GROUP

I find from : https://github.com/OHDSI/webapi-wiki/blob/master/Security-Configuration.md
- security.ad.default.import.group: The group to use for importing users from AD into WebAPI's configuration database.

Does not give much detail on what this does.

**Comment by alondhe** [comment]
In the Atlas Config GUI, there's a wizard to allow selecting groups within your LDAP/AD instance and assigning them to roles. 

![image](https://github.com/OHDSI/Broadsea/assets/8037742/68b779ac-f6f5-4209-ab4d-6a1e926038c2)

So you set up WebAPI to get to your LDAP endpoint, then get into assignments in Atlas.

**Comment by gkowalski** [comment]
Ahh thanks ! Good to know .. if we ever get this working with LDAP / AD we'll be able to authorize users.
